### ISSUE TITLE
npm run start error

### ISSUE THREAD

**Issue by mohitgupta1918** [HVish/jecrc-atms#1]
server.js
locals: require('./config/locals.js')  (doesn't exist)

also after renaming locals-sample.js to locals.js
npm run start throws an error:
```

express-session deprecated req.secret; provide secret option server.js:58:9
Server started!! Please visit:  http://localhost:3000 
Error: secret option required for sessions
    at session (/home/mohitg/node_projects/jecrc-atms-master/node_modules/express-session/index.js:199:12)
    at Layer.handle [as handle_request] (/home/mohitg/node_projects/jecrc-atms-master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/mohitg/node_projects/jecrc-atms-master/node_modules/express/lib/router/index.js:317:13)
    at /home/mohitg/node_projects/jecrc-atms-master/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/mohitg/node_projects/jecrc-atms-master/node_modules/express/lib/router/index.js:335:12)
    at next (/home/mohitg/node_projects/jecrc-atms-master/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/mohitg/node_projects/jecrc-atms-master/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (/home/mohitg/node_projects/jecrc-atms-master/node_modules/send/index.js:282:17)
```

**Comment by HVish** [comment]
locals.js is the file to store all your private credentials which are not to be pushed on git. For example username and password for your database. 
The locals-sample.js is to know all keys required for locals.js file. So duplicate locals-sample.js to locals.js then fill values for all keys.
For the above error you didn't provided any secret key for express-session. You have to provide any value just like your private password. And value for all keys is required as mentioned in locals-sample.js

**Comment by HVish** [comment]
Please refer to https://github.com/HVish/node-framework/blob/master/README.md to understand the directory structure of the project.
